language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install g++
script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - cmake CMakeLists.txt
    - cmake  --build . --target neat
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T MorpheusMatrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukodo-kakaku:$BINTRAY_API_KEY  "https://api.bintray.com/content/prinus/Morfeus/$TRAVIS_BUILD_NUMBER/MorpheusMatrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    all_branches: true 
