language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - cmake CMakeLists.txt
    - cmake  --build . --target neat
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T MorpheusMatrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukodo-kakaku:$BINTRAY_API_KEY  "https://api.bintray.com/content/prinus/Morfeus/$TRAVIS_BUILD_NUMBER/MorpheusMatrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    all_branches: true 
