language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install g++-7 cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script:
  - gcc --version
  - g++ --version
  - cmake --version
  - cmake .
  - cmake --build .
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T MorpheusMatrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukodo-kakaku:$BINTRAY_API_KEY  "https://api.bintray.com/content/prinus/Morfeus/$TRAVIS_BUILD_NUMBER/MorpheusMatrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    all_branches: true
